# Generated by Django 4.2.8 on 2025-12-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='is_public',
        ),
        migrations.AddField(
            model_name='share',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('unlisted', '不公开 (仅链接/ID可见)'), ('private', '私有 (仅自己可见)')], default='public', max_length=10, verbose_name='可见性'),
        ),
    ]
