# Generated by Django 4.2.8 on 2025-12-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0003_remove_share_is_public_share_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
