# Generated by Django 4.2.8 on 2025-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shares", "0004_alter_share_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="approved",
                max_length=10,
                verbose_name="审核状态",
            ),
        ),
    ]
