# Generated by Django 3.2.25 on 2026-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_nsfw',
            field=models.BooleanField(default=False, verbose_name='可能令人不适'),
        ),
        migrations.AddField(
            model_name='share',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='含剧透内容'),
        ),
    ]
