# Generated by Django 3.2.25 on 2026-01-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_auto_20260102_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='原创'),
        ),
        migrations.AlterField(
            model_name='share',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='可能包含剧透'),
        ),
    ]
