# Generated by Django 3.2.25 on 2026-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0008_auto_20260102_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='category',
            field=models.CharField(choices=[('entertainment', '娱乐'), ('combat', '战斗')], default='entertainment', max_length=20, verbose_name='分类'),
        ),
    ]
