# Generated by Django 3.2.25 on 2026-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0010_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            # CKEditor RichTextField used the same database representation as
            # TextField. Keep the historical operation and migration name, but
            # use Django's built-in field so fresh replays need no retired UI
            # package.
            field=models.TextField(verbose_name='内容'),
        ),
    ]
