# Generated by Django 4.2.8 on 2026-01-02 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shares", "0011_alter_announcement_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "站点动态",
                "verbose_name_plural": "站点动态",
            },
        ),
    ]
