# Generated by Django 3.2.25 on 2026-01-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0012_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '合集',
                'verbose_name_plural': '合集',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.collection')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.share')),
            ],
            options={
                'verbose_name': '合集项',
                'verbose_name_plural': '合集项',
                'ordering': ['order', 'added_at'],
                'unique_together': {('collection', 'share')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='shares',
            field=models.ManyToManyField(related_name='collections', through='shares.CollectionItem', to='shares.Share', verbose_name='包含的分享'),
        ),
    ]
