# Generated by Django 3.2.25 on 2026-01-06 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0013_auto_20260104_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建分享'), ('edit', '编辑分享'), ('approve', '审核通过'), ('reject', '审核拒绝'), ('add_collection', '加入合集'), ('remove_collection', '移出合集'), ('report_handle', '处理举报'), ('delete', '删除分享'), ('other', '其他操作')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(blank=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shares.share', verbose_name='关联分享')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
