# Generated by Django 4.2.8 on 2026-01-06 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0014_sharelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_shares', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddField(
            model_name='share',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shares', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
