# Generated by Django 4.2.8 on 2026-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0015_share_favorites_share_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='copies',
            field=models.IntegerField(default=0, verbose_name='复制次数'),
        ),
    ]
