# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0016_add_copies_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_feed_mode',
            field=models.CharField(
                choices=[('paginated', '分页浏览'), ('infinite', '无限滚动')],
                default='paginated',
                max_length=20,
                verbose_name='主页浏览模式'
            ),
        ),
    ]
