# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0017_userprofile_home_feed_mode'),
    ]

    operations = [
        # Change the default for profiles created from this point onward only.
        # Existing rows may already contain an explicit user preference, so a
        # default change must never rewrite either supported value.
        migrations.AlterField(
            model_name='userprofile',
            name='home_feed_mode',
            field=models.CharField(
                choices=[('paginated', '分页'), ('infinite', '瀑布')],
                default='infinite',
                max_length=20,
                verbose_name='主页浏览模式'
            ),
        ),
    ]
