# Generated by Codex on 2026-05-15

from django.db import migrations, models


def move_default_profiles_to_waterfall(apps, schema_editor):
    UserProfile = apps.get_model('shares', 'UserProfile')
    UserProfile.objects.filter(home_feed_mode='paginated').update(home_feed_mode='infinite')


def move_waterfall_profiles_to_paginated(apps, schema_editor):
    UserProfile = apps.get_model('shares', 'UserProfile')
    UserProfile.objects.filter(home_feed_mode='infinite').update(home_feed_mode='paginated')


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0017_userprofile_home_feed_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_feed_mode',
            field=models.CharField(
                choices=[('paginated', '分页'), ('infinite', '瀑布')],
                default='infinite',
                max_length=20,
                verbose_name='主页浏览模式'
            ),
        ),
        migrations.RunPython(move_default_profiles_to_waterfall, move_waterfall_profiles_to_paginated),
    ]
