# Generated by Django 4.2.8 on 2026-05-20 15:27

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError
import django.db.models.deletion


def guard_moderation_data_before_reverse(apps, schema_editor):
    """Refuse to drop moderation data introduced by this migration."""
    database_alias = schema_editor.connection.alias
    SiteMessage = apps.get_model('shares', 'SiteMessage')
    Report = apps.get_model('shares', 'Report')
    Share = apps.get_model('shares', 'Share')

    if SiteMessage.objects.using(database_alias).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while SiteMessage rows exist.'
        )
    if Report.objects.using(database_alias).exclude(resolution_reason='').exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Report.resolution_reason data exists.'
        )
    if Share.objects.using(database_alias).exclude(review_feedback='').exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.review_feedback data exists.'
        )
    if Share.objects.using(database_alias).filter(reviewed_at__isnull=False).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.reviewed_at data exists.'
        )
    if Share.objects.using(database_alias).filter(reviewed_by__isnull=False).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.reviewed_by data exists.'
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0018_default_home_feed_waterfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution_reason',
            field=models.TextField(blank=True, verbose_name='处理说明'),
        ),
        migrations.AddField(
            model_name='share',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='最近一次审核反馈'),
        ),
        migrations.AddField(
            model_name='share',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='share',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shares', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('share_rejected', '分享审核未通过'), ('report_dismissed', '举报未采纳'), ('report_resolved', '举报已处理'), ('share_takedown', '分享被下架')], max_length=30, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_messages', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_messages', to='shares.report', verbose_name='关联举报')),
                ('related_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_messages', to='shares.share', verbose_name='关联分享')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_site_messages', to=settings.AUTH_USER_MODEL, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='shares_site_recipie_ea589e_idx')],
            },
        ),
        # Reverse operations run in reverse order, so this guard executes before
        # any table or field introduced above can be removed.
        migrations.RunPython(
            migrations.RunPython.noop,
            guard_moderation_data_before_reverse,
        ),
    ]
