# Generated by Django 4.2.8 on 2026-05-20 15:27

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError
import django.db.models.deletion


SQLITE_SEQUENCE_FLOOR_TABLE = 'shares_migration_0019_sqlite_sequence_floor'
SQLITE_SEQUENCE_FLOOR_OWNER = (
    'ffxivshare.shares.0019.sqlite-sequence-floor.v1'
)


def _sequence_floor_create_sql(connection):
    quoted_table = connection.ops.quote_name(SQLITE_SEQUENCE_FLOOR_TABLE)
    return (
        f'CREATE TABLE {quoted_table} ('
        '"table_name" TEXT NOT NULL, '
        '"sequence_floor" INTEGER NOT NULL CHECK ('
        'typeof("sequence_floor") = \'integer\' '
        'AND "sequence_floor" >= 0), '
        '"migration_owner" TEXT NOT NULL CHECK ('
        f'"migration_owner" = \'{SQLITE_SEQUENCE_FLOOR_OWNER}\'))'
    )


def _normalize_schema_sql(sql):
    return ' '.join(sql.split()) if isinstance(sql, str) else None


def _validate_sequence_rows(rows, *, source):
    validated = []
    seen_names = set()
    for row_number, row in enumerate(rows, start=1):
        if not isinstance(row, (tuple, list)) or len(row) != 2:
            raise RuntimeError(
                f'{source} row {row_number} must contain exactly two values.'
            )
        table_name, sequence_floor = row
        if not isinstance(table_name, str) or not table_name:
            raise RuntimeError(
                f'{source} row {row_number} has an invalid table name.'
            )
        if (
            isinstance(sequence_floor, bool)
            or not isinstance(sequence_floor, int)
            or sequence_floor < 0
        ):
            raise RuntimeError(
                f'{source} row {row_number} has an invalid sequence value.'
            )
        comparison_name = table_name.casefold()
        if comparison_name in seen_names:
            raise RuntimeError(
                f'{source} contains duplicate table name {table_name!r}.'
            )
        seen_names.add(comparison_name)
        validated.append((table_name, sequence_floor))
    return validated


def _objects_using_sequence_floor_name(cursor):
    cursor.execute(
        """
        SELECT type, name, tbl_name
        FROM sqlite_schema
        WHERE lower(name) = lower(%s) OR lower(tbl_name) = lower(%s)
        ORDER BY type, name
        """,
        [SQLITE_SEQUENCE_FLOOR_TABLE, SQLITE_SEQUENCE_FLOOR_TABLE],
    )
    return cursor.fetchall()


def _validate_owned_sequence_floor_table(cursor, *, allow_missing):
    objects = _objects_using_sequence_floor_name(cursor)
    if not objects:
        if allow_missing:
            return False
        raise RuntimeError(
            f'SQLite sequence floor table {SQLITE_SEQUENCE_FLOOR_TABLE!r} is missing.'
        )
    expected_object = (
        'table',
        SQLITE_SEQUENCE_FLOOR_TABLE,
        SQLITE_SEQUENCE_FLOOR_TABLE,
    )
    if objects != [expected_object]:
        raise RuntimeError(
            'Refusing to use the SQLite sequence floor name because it is '
            f'owned by unexpected schema objects: {objects!r}.'
        )

    quoted_table = cursor.db.ops.quote_name(SQLITE_SEQUENCE_FLOOR_TABLE)
    cursor.execute(f'PRAGMA table_info({quoted_table})')
    columns = cursor.fetchall()
    expected_columns = [
        (0, 'table_name', 'TEXT', 1, None, 0),
        (1, 'sequence_floor', 'INTEGER', 1, None, 0),
        (2, 'migration_owner', 'TEXT', 1, None, 0),
    ]
    if columns != expected_columns:
        raise RuntimeError(
            'SQLite sequence floor table has an unexpected schema: '
            f'{columns!r}.'
        )
    cursor.execute(
        'SELECT sql FROM sqlite_schema WHERE type = \'table\' AND name = %s',
        [SQLITE_SEQUENCE_FLOOR_TABLE],
    )
    stored_create_sql = cursor.fetchone()[0]
    expected_create_sql = _sequence_floor_create_sql(cursor.db)
    if _normalize_schema_sql(stored_create_sql) != _normalize_schema_sql(
        expected_create_sql
    ):
        raise RuntimeError(
            'SQLite sequence floor table does not carry the expected '
            'migration ownership signature.'
        )
    return True


def _read_captured_sequence_rows(cursor, quoted_table):
    cursor.execute(
        f'SELECT "table_name", "sequence_floor", "migration_owner" '
        f'FROM {quoted_table} ORDER BY "table_name"'
    )
    sequence_rows = []
    for row_number, row in enumerate(cursor.fetchall(), start=1):
        table_name, sequence_floor, migration_owner = row
        if (
            not isinstance(migration_owner, str)
            or migration_owner != SQLITE_SEQUENCE_FLOOR_OWNER
        ):
            raise RuntimeError(
                'SQLite sequence floor table row '
                f'{row_number} has an invalid migration owner.'
            )
        sequence_rows.append((table_name, sequence_floor))
    return _validate_sequence_rows(
        sequence_rows,
        source=SQLITE_SEQUENCE_FLOOR_TABLE,
    )


def capture_sqlite_sequence_floors(apps, schema_editor):
    """Capture every SQLite AUTOINCREMENT high-water mark before table rebuilds."""
    connection = schema_editor.connection
    if connection.vendor != 'sqlite':
        return

    quoted_table = connection.ops.quote_name(SQLITE_SEQUENCE_FLOOR_TABLE)
    with connection.cursor() as cursor:
        if _objects_using_sequence_floor_name(cursor):
            raise RuntimeError(
                'Refusing to overwrite an existing SQLite schema object named '
                f'{SQLITE_SEQUENCE_FLOOR_TABLE!r}.'
            )

        cursor.execute(
            "SELECT type FROM sqlite_schema WHERE name = 'sqlite_sequence'"
        )
        sqlite_sequence_object = cursor.fetchall()
        if sqlite_sequence_object not in ([], [('table',)]):
            raise RuntimeError(
                'sqlite_sequence is not an ordinary SQLite table: '
                f'{sqlite_sequence_object!r}.'
            )
        if sqlite_sequence_object:
            cursor.execute('SELECT name, seq FROM sqlite_sequence ORDER BY name')
            source_rows = _validate_sequence_rows(
                cursor.fetchall(),
                source='sqlite_sequence',
            )
        else:
            source_rows = []

        cursor.execute(_sequence_floor_create_sql(connection))
        if source_rows:
            cursor.executemany(
                f'INSERT INTO {quoted_table} '
                '("table_name", "sequence_floor", "migration_owner") '
                'VALUES (%s, %s, %s)',
                [
                    (table_name, sequence_floor, SQLITE_SEQUENCE_FLOOR_OWNER)
                    for table_name, sequence_floor in source_rows
                ],
            )
        captured_rows = _read_captured_sequence_rows(cursor, quoted_table)
        if captured_rows != source_rows:
            raise RuntimeError(
                'SQLite sequence floor capture did not reproduce the source '
                'sqlite_sequence rows exactly.'
            )


def cleanup_sqlite_sequence_floors_on_reverse(apps, schema_editor):
    """Remove only the exact migration-owned table when 0019 reverses."""
    connection = schema_editor.connection
    if connection.vendor != 'sqlite':
        return

    quoted_table = connection.ops.quote_name(SQLITE_SEQUENCE_FLOOR_TABLE)
    with connection.cursor() as cursor:
        try:
            exists = _validate_owned_sequence_floor_table(
                cursor,
                allow_missing=True,
            )
        except RuntimeError as exc:
            raise IrreversibleError(str(exc)) from exc
        if exists:
            try:
                _read_captured_sequence_rows(cursor, quoted_table)
            except RuntimeError as exc:
                raise IrreversibleError(str(exc)) from exc
            cursor.execute(f'DROP TABLE {quoted_table}')


def guard_moderation_data_before_reverse(apps, schema_editor):
    """Refuse to drop moderation data introduced by this migration."""
    database_alias = schema_editor.connection.alias
    SiteMessage = apps.get_model('shares', 'SiteMessage')
    Report = apps.get_model('shares', 'Report')
    Share = apps.get_model('shares', 'Share')

    if SiteMessage.objects.using(database_alias).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while SiteMessage rows exist.'
        )
    if Report.objects.using(database_alias).exclude(resolution_reason='').exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Report.resolution_reason data exists.'
        )
    if Share.objects.using(database_alias).exclude(review_feedback='').exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.review_feedback data exists.'
        )
    if Share.objects.using(database_alias).filter(reviewed_at__isnull=False).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.reviewed_at data exists.'
        )
    if Share.objects.using(database_alias).filter(reviewed_by__isnull=False).exists():
        raise IrreversibleError(
            'Cannot reverse migration 0019 while Share.reviewed_by data exists.'
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0018_default_home_feed_waterfall'),
    ]

    operations = [
        migrations.RunPython(
            capture_sqlite_sequence_floors,
            cleanup_sqlite_sequence_floors_on_reverse,
            atomic=True,
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_reason',
            field=models.TextField(blank=True, verbose_name='处理说明'),
        ),
        migrations.AddField(
            model_name='share',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='最近一次审核反馈'),
        ),
        migrations.AddField(
            model_name='share',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='share',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shares', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('share_rejected', '分享审核未通过'), ('report_dismissed', '举报未采纳'), ('report_resolved', '举报已处理'), ('share_takedown', '分享被下架')], max_length=30, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_messages', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_messages', to='shares.report', verbose_name='关联举报')),
                ('related_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_messages', to='shares.share', verbose_name='关联分享')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_site_messages', to=settings.AUTH_USER_MODEL, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='shares_site_recipie_ea589e_idx')],
            },
        ),
        # Reverse operations run in reverse order, so this guard executes before
        # any table or field introduced above can be removed.
        migrations.RunPython(
            migrations.RunPython.noop,
            guard_moderation_data_before_reverse,
        ),
    ]
