# Generated by Django 5.2.16 on 2026-07-10 18:27

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Q


def validate_existing_data(apps, schema_editor):
    """Fail before schema changes when existing rows violate new invariants."""
    UserProfile = apps.get_model('shares', 'UserProfile')
    Share = apps.get_model('shares', 'Share')
    Report = apps.get_model('shares', 'Report')
    CollectionItem = apps.get_model('shares', 'CollectionItem')

    violations = {
        'invalid profile feed mode': UserProfile.objects.exclude(
            home_feed_mode__in=['paginated', 'infinite'],
        ).count(),
        'invalid share category': Share.objects.exclude(
            category__in=['entertainment', 'combat'],
        ).count(),
        'invalid share visibility': Share.objects.exclude(
            visibility__in=['public', 'unlisted', 'private'],
        ).count(),
        'invalid share status': Share.objects.exclude(
            status__in=['pending', 'approved', 'rejected'],
        ).count(),
        'negative share counters': Share.objects.filter(
            Q(views__lt=0) | Q(copies__lt=0),
        ).count(),
        'pending shares with review metadata': Share.objects.filter(
            status='pending',
        ).filter(
            Q(reviewed_at__isnull=False) | Q(reviewed_by__isnull=False),
        ).count(),
        'reviewer without review time': Share.objects.filter(
            reviewed_by__isnull=False,
            reviewed_at__isnull=True,
        ).count(),
        'invalid report status': Report.objects.exclude(
            status__in=['pending', 'resolved', 'dismissed'],
        ).count(),
        'pending reports with resolution data': Report.objects.filter(
            status='pending',
        ).filter(
            Q(resolved_at__isnull=False)
            | Q(resolved_by__isnull=False)
            | ~Q(resolution_reason='')
        ).count(),
        'finished reports without resolution time': Report.objects.exclude(
            status='pending',
        ).filter(resolved_at__isnull=True).count(),
        'duplicate pending reports': Report.objects.filter(
            status='pending',
        ).values('share_id', 'reporter_id').annotate(
            row_count=Count('id'),
        ).filter(row_count__gt=1).count(),
        'duplicate collection order slots': CollectionItem.objects.values(
            'collection_id', 'order',
        ).annotate(
            row_count=Count('id'),
        ).filter(row_count__gt=1).count(),
    }
    failures = [
        f'{label}: {count}'
        for label, count in violations.items()
        if count
    ]
    if failures:
        details = '; '.join(failures)
        raise RuntimeError(
            'Existing data violates the new integrity constraints. '
            f'No data was changed. Resolve or migrate these rows first: {details}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0020_replace_ckeditor_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_existing_data,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_id',
            field=models.CharField(editable=False, max_length=21, unique=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-created_at'], name='announcement_active_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['author', 'is_public', '-updated_at'], name='collection_author_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'order', 'added_at'], name='collection_item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'share', '-created_at'], name='report_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='report_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='share_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['author', '-created_at'], name='share_author_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['share', '-created_at'], name='share_log_share_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelog',
            index=models.Index(fields=['user', '-created_at'], name='share_log_user_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemessage',
            index=models.Index(fields=['recipient', 'archived_at', '-created_at'], name='message_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'share'), name='collection_share_unique'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'order'), name='collection_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'resolved', 'dismissed'])), name='report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('resolution_reason', '')), _connector='OR'), name='report_pending_unresolved'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), ('resolved_at__isnull', False), _connector='OR'), name='report_finished_has_time'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('share', 'reporter'), name='report_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['entertainment', 'combat'])), name='share_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'unlisted', 'private'])), name='share_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='share_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('views__gte', 0)), name='share_views_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('copies__gte', 0)), name='share_copies_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), _connector='OR'), name='share_pending_unreviewed'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', True), _connector='OR'), name='share_reviewer_has_time'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('home_feed_mode__in', ['paginated', 'infinite'])), name='profile_feed_mode_valid'),
        ),
    ]
