# Generated by Django 5.2.16 on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


REVIEW_REJECTED = 'review_rejected'
REPORT_TAKEDOWN = 'report_takedown'
LEGACY_PRIVATE = 'legacy_private'
MISSING_REVIEW_REASON = '历史审核拒绝记录未保存原因'
MISSING_REPORT_REASON = '历史举报下架记录未保存处理说明'
LEGACY_PRIVATE_REASON = '历史私密状态来源待人工确认'


def backfill_share_restrictions(apps, schema_editor):
    """Recover active moderation restrictions without rewriting user visibility."""
    Share = apps.get_model('shares', 'Share')
    Report = apps.get_model('shares', 'Report')
    ShareLog = apps.get_model('shares', 'ShareLog')

    latest_resolved_reports = {}
    for report in Report.objects.filter(status='resolved').order_by(
        'share_id', '-resolved_at', '-pk',
    ).iterator(chunk_size=1000):
        latest_resolved_reports.setdefault(report.share_id, report)

    latest_review_events = {}
    for log in ShareLog.objects.filter(action__in=['approve', 'reject']).order_by(
        'share_id', '-created_at', '-pk',
    ).iterator(chunk_size=1000):
        events = latest_review_events.setdefault(log.share_id, {})
        events.setdefault(log.action, log)

    updates = []
    for share in Share.objects.all().iterator(chunk_size=1000):
        resolved_report = latest_resolved_reports.get(share.pk)
        if resolved_report is not None:
            share.restriction_state = REPORT_TAKEDOWN
            share.restriction_reason = (
                resolved_report.resolution_reason.strip()
                or MISSING_REPORT_REASON
            )
            share.restricted_at = (
                resolved_report.resolved_at
                or resolved_report.created_at
                or share.updated_at
            )
            share.restricted_by_id = resolved_report.resolved_by_id
            updates.append(share)
            continue

        events = latest_review_events.get(share.pk, {})
        rejected_log = events.get('reject')
        approved_log = events.get('approve')
        rejected_is_active = share.status == 'rejected'
        if not rejected_is_active and rejected_log is not None:
            rejected_key = (rejected_log.created_at, rejected_log.pk)
            approved_key = (
                (approved_log.created_at, approved_log.pk)
                if approved_log is not None else None
            )
            rejected_is_active = approved_key is None or rejected_key > approved_key

        if rejected_is_active:
            share.restriction_state = REVIEW_REJECTED
            share.restriction_reason = (
                share.review_feedback.strip()
                or (rejected_log.details.strip() if rejected_log is not None else '')
                or MISSING_REVIEW_REASON
            )
            share.restricted_at = (
                share.reviewed_at
                or (rejected_log.created_at if rejected_log is not None else None)
                or share.updated_at
            )
            share.restricted_by_id = (
                share.reviewed_by_id
                or (rejected_log.user_id if rejected_log is not None else None)
            )
            updates.append(share)
            continue

        if share.visibility == 'private':
            share.restriction_state = LEGACY_PRIVATE
            share.restriction_reason = LEGACY_PRIVATE_REASON
            share.restricted_at = share.updated_at or share.created_at
            share.restricted_by_id = None
            updates.append(share)

    if updates:
        Share.objects.bulk_update(
            updates,
            [
                'restriction_state',
                'restriction_reason',
                'restricted_at',
                'restricted_by',
            ],
            batch_size=500,
        )


def reverse_share_restrictions(apps, schema_editor):
    """Only an empty development database can safely remove restriction data."""
    Share = apps.get_model('shares', 'Share')
    if Share.objects.exists():
        raise IrreversibleError(
            '0022 contains moderation restrictions and audit-preservation changes; '
            'restore the pre-migration database backup instead of reversing it.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0021_add_data_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='share',
            name='share_feed_idx',
        ),
        migrations.AddField(
            model_name='share',
            name='restricted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容限制时间'),
        ),
        migrations.AddField(
            model_name='share',
            name='restricted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_shares', to=settings.AUTH_USER_MODEL, verbose_name='内容限制操作人'),
        ),
        migrations.AddField(
            model_name='share',
            name='restriction_reason',
            field=models.TextField(blank=True, verbose_name='内容限制原因'),
        ),
        migrations.AddField(
            model_name='share',
            name='restriction_state',
            field=models.CharField(choices=[('clear', '无限制'), ('review_rejected', '审核拒绝限制'), ('report_takedown', '举报下架限制'), ('legacy_private', '历史私密待确认')], default='clear', max_length=20, verbose_name='内容限制状态'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人'),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='action',
            field=models.CharField(choices=[('create', '创建分享'), ('edit', '编辑分享'), ('approve', '审核通过'), ('reject', '审核拒绝'), ('confirm_restriction', '确认维持内容限制'), ('release_restriction', '解除内容限制'), ('add_collection', '加入合集'), ('remove_collection', '移出合集'), ('report_handle', '处理举报'), ('delete', '删除分享'), ('other', '其他操作')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='message_type',
            field=models.CharField(choices=[('share_rejected', '分享审核未通过'), ('report_dismissed', '举报未采纳'), ('report_resolved', '举报已处理'), ('share_takedown', '分享被下架'), ('share_restored', '分享限制已解除')], max_length=30, verbose_name='消息类型'),
        ),
        migrations.RunPython(
            backfill_share_restrictions,
            reverse_share_restrictions,
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['restriction_state', 'visibility', 'status', '-created_at'], name='share_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('restriction_state__in', ['clear', 'review_rejected', 'report_takedown', 'legacy_private'])), name='share_restriction_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('restricted_at__isnull', True), ('restricted_by__isnull', True), ('restriction_reason', ''), ('restriction_state', 'clear')), models.Q(models.Q(('restriction_state', 'clear'), _negated=True), models.Q(('restriction_reason', ''), _negated=True), ('restricted_at__isnull', False)), _connector='OR'), name='share_restriction_metadata'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('restriction_state', 'clear'), _negated=True), _connector='OR'), name='share_rejected_restricted'),
        ),
    ]
