# Generated by Django 5.2.16 on 2026-07-15

from django.conf import settings
from django.db import migrations
from django.utils import timezone


PROFILE_BACKFILL_BATCH_SIZE = 1_000


def backfill_missing_user_profiles(apps, schema_editor):
    """Create only missing profile rows; preserve every existing profile verbatim."""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('shares', 'UserProfile')
    database = schema_editor.connection.alias
    profile_user_ids = UserProfile.objects.using(database).values('user_id')
    missing_user_ids = User.objects.using(database).exclude(
        pk__in=profile_user_ids,
    ).order_by('pk').values_list('pk', flat=True)

    pending = []
    for user_id in missing_user_ids.iterator(chunk_size=PROFILE_BACKFILL_BATCH_SIZE):
        timestamp = timezone.now()
        pending.append(UserProfile(
            user_id=user_id,
            created_at=timestamp,
            updated_at=timestamp,
        ))
        if len(pending) >= PROFILE_BACKFILL_BATCH_SIZE:
            UserProfile.objects.using(database).bulk_create(
                pending,
                batch_size=PROFILE_BACKFILL_BATCH_SIZE,
                ignore_conflicts=True,
            )
            pending.clear()

    if pending:
        UserProfile.objects.using(database).bulk_create(
            pending,
            batch_size=PROFILE_BACKFILL_BATCH_SIZE,
            ignore_conflicts=True,
        )

    remaining_missing = User.objects.using(database).exclude(
        pk__in=UserProfile.objects.using(database).values('user_id'),
    ).exists()
    if remaining_missing:
        raise RuntimeError(
            'UserProfile backfill did not establish one profile per user.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0022_add_share_restrictions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            backfill_missing_user_profiles,
            migrations.RunPython.noop,
        ),
    ]
