# Generated by Django 5.2.16 on 2026-07-16 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0024_widen_site_message_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['author', '-updated_at', '-id'], name='collection_owner_updated_idx'),
        ),
    ]
